# generated BUILD file
java_library(
	name = "model_oauth/client",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:org_springframework_security_oauth_spring_security_oauth2"],
)
