description = "CloudFoundry Identity Model JAR"

dependencies {
    implementation(project(":cloudfoundry-identity-metrics-data"))

    implementation(libs.jacksonDatabind)
    implementation(libs.jacksonAnnotations)

    implementation(libs.jakartaValidationApi)

    implementation(libs.commonsCodec)
    implementation(libs.commonsIo)

    implementation(libs.springWeb)
    implementation(libs.springWebMvc)
    implementation(libs.springSecurityConfig)

    implementation(libs.nimbusJwt)

    implementation(libs.slf4jApi)

    testImplementation(libs.springBootStarterTest)
    testImplementation(libs.hamcrest)
    testImplementation(libs.junit5JupiterApi)
    testImplementation(libs.junit5JupiterParams)

    testImplementation(libs.jsonAssert)
}

configurations {
    testArtifacts
}

tasks.register('testJar', Jar) {
    dependsOn(tasks.testClasses)
    archiveClassifier = 'tests'
    from(sourceSets.test.output)
}

artifacts {
    testArtifacts(testJar)
}

apply(from: file("build_properties.gradle"))

processResources {
    //maven replaces project.artifactId in the log4j2.properties file
    //https://www.pivotaltracker.com/story/show/74344574
    filter { line -> line.contains('${project.artifactId}') ? line.replace('${project.artifactId}', 'cloudfoundry-identity-model') : line }
}

integrationTest {}.onlyIf { //disable since we don't have any
    false
}
