version: 2
updates:
- package-ecosystem: npm
  directory: "/uaa"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "org.springframework.boot:*"
    versions:
    - ">= 4"  # Stay in Spring Boot major version 3 and do updates manually.
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
