--
-- Copyright (c) [2016] Microsoft, Inc. All Rights Reserved.
--
-- This product is licensed to you under the Apache License, Version 2.0 (the "License").
-- You may not use this product except in compliance with the License.
--
-- This product includes a number of subcomponents with
-- separate copyright notices and license terms. Your use of these
-- subcomponents is subject to the terms and conditions of the
-- subcomponent's license, as noted in the LICENSE file.
--
UPDATE identity_provider SET config='{"passwordPolicy":{"minLength":6,"maxLength":128,"requireUpperCaseCharacter":1,"requireLowerCaseCharacter":1,"requireDigit":1,"requireSpecialCharacter":0,"expirePasswordInMonths":0}}' WHERE origin_key='uaa' AND identity_zone_id <> 'uaa';