#!/bin/sh

# If `realpath` isn't installed on your Mac, install it with `brew install coreutils`.
export LOGIN_CONFIG_URL=file://$(realpath uaa/src/main/resources/required_configuration.yml)
./gradlew run
