# generated BUILD file
java_library(
	name = "model_oauth/token",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:com_fasterxml_jackson_core_jackson_databind","//third_party:org_springframework_security_oauth_spring_security_oauth2","//third_party:com_fasterxml_jackson_core_jackson_core","//third_party:org_springframework_spring_core","//model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk:model_oauth/jwk","//third_party:commons_codec_commons_codec","//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util"],
)
