#@data/values
#@ load("@ytt:overlay", "overlay")
---
jwt:
  #@overlay/replace
  policy:
    activeKeyId: other_active_key2
    keys:
      other_active_key2:
        signingKey: |
          this
          is
          a
          multiline
          string
      unused_key_id:
        signingKey: unused_signing_key
