# generated BUILD file
java_library(
	name = "model_approval",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//model/src/main/java/org/cloudfoundry/identity/uaa/impl:model_impl","//third_party:com_fasterxml_jackson_core_jackson_databind","//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:com_fasterxml_jackson_core_jackson_core"],
)
