# generated BUILD file
java_library(
	name = "model_provider",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:org_springframework_spring_core","//model/src/main/java/org/cloudfoundry/identity/uaa/constants:model_constants","//third_party:com_fasterxml_jackson_core_jackson_databind","//model/src/main/java/org/cloudfoundry/identity/uaa/authentication:model_authentication","//third_party:com_fasterxml_jackson_core_jackson_core","//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util","//third_party:javax_validation_validation_api","//model/src/main/java/org/cloudfoundry/identity/uaa/login:model_login"],
)
