--
-- Cloud Foundry 2012.02.03 Beta
-- Copyright (c) [2009-2012] VMware, Inc. All Rights Reserved.
--
-- This product is licensed to you under the Apache License, Version 2.0 (the "License").
-- You may not use this product except in compliance with the License.
--
-- This product includes a number of subcomponents with
-- separate copyright notices and license terms. Your use of these
-- subcomponents is subject to the terms and conditions of the
-- subcomponent's license, as noted in the LICENSE file.
--
-- Autogenerated: do not edit this file

DROP TABLE  USERS IF EXISTS;
DROP TABLE  SEC_AUDIT IF EXISTS;
DROP TABLE  OAUTH_CLIENT_DETAILS IF EXISTS;
DROP TABLE  GROUP_MEMBERSHIP IF EXISTS;
DROP TABLE  GROUPS IF EXISTS;
DROP TABLE  oauth_client_token IF EXISTS;
DROP TABLE  oauth_access_token IF EXISTS;
DROP TABLE  oauth_refresh_token IF EXISTS;
DROP TABLE  oauth_code IF EXISTS;
DROP TABLE  AUTHZ_APPROVALS IF EXISTS;