# generated BUILD file
java_library(
	name = "model_account",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:com_fasterxml_jackson_core_jackson_databind","//model/src/main/java/org/cloudfoundry/identity/uaa/codestore:model_codestore","//model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token:model_oauth/token"],
)
