---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uaa-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: uaa
          servicePort: 8080