# generated BUILD file
java_library(
	name = "model_login",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:org_springframework_spring_core"],
)
