apply(plugin: "war")

description = "CloudFoundry Identity Server JAR"

dependencies {
    implementation(project(":cloudfoundry-identity-metrics-data"))
    implementation(project(":cloudfoundry-identity-model"))

    implementation(libs.tomcatJdbc)
    providedCompile(libs.tomcatEmbed)

    implementation(libs.jacksonDatabind)
    implementation(libs.jsonPath) {
        exclude(module: "json-smart")
    }
    implementation(libs.springBeans)
    implementation(libs.springContext)
    implementation(libs.springContextSupport)
    implementation(libs.springTx)
    implementation(libs.springJdbc)
    implementation(libs.springWeb)
    implementation(libs.springSecurityCore)
    implementation(libs.springSecurityWeb)
    implementation(libs.springSecurityConfig)
    implementation(libs.springBootStarterMail)
    implementation(libs.openSamlApi)
    implementation(libs.springSecuritySamlServiceProvider)
    implementation(libs.xmlSecurity)
    implementation(libs.springSessionJdbc)

    implementation(libs.bouncyCastleFipsProv)
    implementation(libs.bouncyCastlePkixFips)
    implementation(libs.bouncyCastleTlsFips)
    implementation(libs.bouncyCastleUtilFips)

    implementation(libs.guava)

    implementation(libs.aspectJWeaver)

    implementation(libs.thymeLeaf) {
        exclude(module: "ognl")
    }
    implementation(libs.thymeleafSpring) {
        exclude(module: "ognl")
    }
    implementation(libs.thymeleafDialect) {
        exclude(module: "ognl")
    }
    implementation(libs.thymeleafExtrasSpringSecurity) {
        exclude(module: "ognl")
    }

    implementation(libs.unboundIdScimSdk) {
        exclude(module: "servlet-api")
        exclude(module: "commons-logging")
        exclude(module: "httpclient")
        exclude(module: "wink-client-apache-httpclient")
        exclude(module: "json")
    }

    implementation(libs.hibernateValidator)
    implementation(libs.flywayHsqlDb)
    implementation(libs.flywayMySql)
    implementation(libs.flywayPostgresql)
    implementation(libs.hsqldb)

    implementation(libs.snakeyaml)
    implementation(libs.velocity)

    implementation(libs.springWebMvc)
    implementation(libs.springSecurityLdap)
    implementation(libs.springLdapCore)
    implementation(libs.apacheLdapApi) {
        exclude(module: "slf4j-api")
        exclude(module: "mina-core")
    }

    implementation(libs.passay)

    implementation(libs.slf4jImpl)
    implementation(libs.log4jCore)

    implementation(libs.nimbusJwt)
    implementation(libs.orgJson)

    implementation(libs.apacheHttpClient)

    testImplementation(project(path: ":cloudfoundry-identity-model", configuration: "testArtifacts"))

    testImplementation(libs.springTest)

    testImplementation(libs.bytebuddy)
    testImplementation(libs.bytebuddyagent)
    testImplementation(libs.mockitoJunit5)

    testImplementation(libs.postgresql)
    testImplementation(libs.mariaJdbcDriver)

    testImplementation(libs.tomcatElApi)
    testImplementation(libs.tomcatJasperEl)
    testImplementation(libs.tomcatJdbc)

    testImplementation(libs.jsonPathAssert)
    testImplementation(libs.xmlUnit)
    testImplementation(libs.awaitility)

    implementation(libs.commonsIo)
}

configurations.all {
    exclude(group: "org.beanshell", module: "bsh-core")
    exclude(group: "org.apache-extras.beanshell", module: "bsh")
    exclude(group: "com.fasterxml.woodstox", module: "woodstox-core")
    exclude(group: "commons-beanutils", module: "commons-beanutils")
    exclude(group: "commons-collections", module: "commons-collections")

    // Exclude non-FIPS bouncycastle libs, and use Shadow library for FIPS compliance
    exclude(group: "org.bouncycastle", module: "bcpkix-jdk15on")
    exclude(group: "org.bouncycastle", module: "bcprov-jdk15on")
    exclude(group: "org.bouncycastle", module: "bcutil-jdk15on")
    exclude(group: "org.bouncycastle", module: "bcprov-jdk18on")
    exclude(group: "org.bouncycastle", module: "bcpkix-jdk18on")
    exclude(group: "org.bouncycastle", module: "bcutil-jdk18on")
}

jar {
    exclude("org/cloudfoundry/identity/uaa/web/tomcat/UaaStartupFailureListener.*")
}

processResources {
    //maven replaces project.artifactId in the log4j2.properties file
    //https://www.pivotaltracker.com/story/show/74344574
    filter { line -> line.contains('${project.artifactId}') ? line.replace('${project.artifactId}', 'cloudfoundry-identity-server') : line }
}

integrationTest {}.onlyIf { //disable since we don't have any
    false
}

task tomcatListenerJar(type: Jar) {
    archiveBaseName = "tomcat-listener"
    from(sourceSets.main.output)
    include("org/cloudfoundry/identity/uaa/web/tomcat/UaaStartupFailureListener.*")
}

artifacts {
    archives(tomcatListenerJar)
}
