kind: Service
apiVersion: v1
metadata:
  name: mysql-db-svc
spec:
  selector:
    app: mysql-server
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 32002
  type: NodePort
