# generated BUILD file
java_library(
	name = "model_oauth/jwk",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:org_springframework_spring_core","//third_party:commons_codec_commons_codec","//third_party:com_fasterxml_jackson_core_jackson_databind","//third_party:com_fasterxml_jackson_core_jackson_core","//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util","//third_party:com_fasterxml_jackson_core_jackson_annotations"],
)
