ruby '>= 3.0'
source 'https://rubygems.org'

gem 'bundler', '~> 2.2'
# Middleman
gem 'middleman', '~> 4.4'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.16.0'
gem 'sass'
gem 'webrick'
gem 'mini_racer', '~> 0.12.0', :platform => :ruby
