# generated BUILD file
java_library(
	name = "model_codestore",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_databind","//third_party:com_fasterxml_jackson_core_jackson_annotations"],
)
