# generated BUILD file
java_library(
	name = "model_zone",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//model/src/main/java/org/cloudfoundry/identity/uaa/authentication:model_authentication","//third_party:org_springframework_spring_web","//third_party:org_springframework_spring_core","//model/src/main/java/org/cloudfoundry/identity/uaa/constants:model_constants","//model/src/main/java/org/cloudfoundry/identity/uaa/saml:model_saml","//model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token:model_oauth/token","//third_party:javax_validation_validation_api","//model/src/main/java/org/cloudfoundry/identity/uaa/login:model_login"],
)
