java_library(
    name = "metrics-data",
    visibility = ["//visibility:public"],
    resources = glob([
        "src/main/resources/**",
    ]),
    exports = [
        "//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/metrics:metrics-data_metrics",
        "//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util",
    ],
)
