java_library(
    name = "uaa-metrics-data",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    resources = glob([
        "src/main/resources/**",
    ]),
    deps = [
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:org_hamcrest_hamcrest_core",
        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:junit_junit",
        "//third_party:org_hamcrest_hamcrest_all",
    ],
)

