# generated BUILD file
java_library(
	name = "model_mfa",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:com_fasterxml_jackson_core_jackson_core","//third_party:org_springframework_spring_core","//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util","//third_party:com_fasterxml_jackson_core_jackson_databind"],
)
