# generated BUILD file
java_library(
	name = "model_provider/saml/idp",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_core","//third_party:org_springframework_spring_core","//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util","//third_party:com_fasterxml_jackson_core_jackson_databind","//third_party:com_fasterxml_jackson_core_jackson_annotations","//third_party:javax_validation_validation_api"],
)
