#@ load("@ytt:data", "data")
#@ load("ca_certs.star", "has_ca_certs", "ca_certs_to_files")

#@ if has_ca_certs(data.values.ca_certs):
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-ca-certs
type: Opaque
data: #@ ca_certs_to_files(data.values.ca_certs)
#@ end
