#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def database_credentials():
database:
  username: #@ data.values.database.username or ""
  password: #@ data.values.database.password or ""
#@ end

#@ if data.values.database.username or data.values.database.password:
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-database-credentials
type: Opaque
stringData:
  database_credentials.yml: #@ yaml.encode(database_credentials())
#@ end
