#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("jwt_policy_signing_keys.star", "signing_keys")

#@ def uaa_yml_signing_keys():
jwt:
  token:
    policy: #@ signing_keys(data.values.jwt.policy)
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-jwt-policy-signing-keys
type: Opaque
stringData:
  jwt_policy_signing_keys.yml: #@ yaml.encode(uaa_yml_signing_keys())
