#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("saml_keys.star", "saml_keys")

#@ def uaa_saml_keys():
login: #@ saml_keys(data.values.login)
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-saml-keys
type: Opaque
stringData:
  saml_keys.yml: #@ yaml.encode(uaa_saml_keys())

