#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ def smtp_credentials():
---
smtp:
  user: #@ data.values.smtp.user or ""
  password: #@ data.values.smtp.password or ""
#@ end

#@ if data.values.smtp.user or data.values.smtp.password:
---
apiVersion: v1
kind: Secret
metadata:
  name: uaa-smtp-credentials
type: Opaque
stringData:
  smtp_credentials.yml: #@ yaml.encode(smtp_credentials())
#@ end
