# generated BUILD file
java_library(
	name = "metrics-data_util",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:com_fasterxml_jackson_core_jackson_core","//third_party:com_fasterxml_jackson_core_jackson_databind"],
)
