apply(plugin: "java")

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":cloudfoundry-identity-metrics-data"))
    implementation(libs.springBootStarter)
    implementation(libs.springBootStarterWeb)
    implementation(libs.springBootStarterLog4j2)
    implementation(libs.statsdClient)
    testImplementation(libs.mockitoJunit5)
    testImplementation(libs.bytebuddy)
    testImplementation(libs.bytebuddyagent)
    implementation(libs.jacksonDatabind)
}

test {
    exclude("org/cloudfoundry/identity/statsd/integration/*.class")
    exclude("**/*IT.class")
}

integrationTest {
    filter {
        includeTestsMatching("org.cloudfoundry.identity.statsd.integration.*")
        includeTestsMatching("*IT")
    }
}
