# generated BUILD file
java_library(
	name = "model_util",
	srcs = glob(["*.java"]),
	visibility = ["//visibility:public"],
	deps = ["//third_party:org_springframework_spring_core","//third_party:com_fasterxml_jackson_core_jackson_annotations","//model/src/main/java/org/cloudfoundry/identity/uaa/constants:model_constants","//model/src/main/java/org/cloudfoundry/identity/uaa/zone:model_zone","//model/src/main/java/org/cloudfoundry/identity/uaa/authentication:model_authentication","//model/src/main/java/org/cloudfoundry/identity/uaa/saml:model_saml","//third_party:com_fasterxml_jackson_core_jackson_databind","//third_party:org_springframework_spring_web","//model/src/main/java/org/cloudfoundry/identity/uaa/oauth/token:model_oauth/token","//third_party:com_fasterxml_jackson_core_jackson_core","//metrics-data/src/main/java/org/cloudfoundry/identity/uaa/util:metrics-data_util","//third_party:javax_validation_validation_api","//third_party:org_springframework_security_spring_security_core","//model/src/main/java/org/cloudfoundry/identity/uaa/login:model_login"],
)
