name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# Run unit tests on CF landscape: Ubuntu with various Bellsoft Liberica Java versions
permissions:
  contents: read

jobs:
  uaa_standalone_test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ '21', '25' ]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: ./gradlew --no-daemon -Dspring.profiles.active=hsqldb -DfailOnPassedAfterRetry=false --no-daemon test
