name: Integration tests on postgresql version 15
on:
  pull_request:
    branches: [ develop ]

permissions:
  pull-requests: read

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: cfidentity/uaa-postgresql-15
      env:
        DB: postgresql
        RUN_TESTS: true
      volumes:
        - ${{ github.workspace }}:/root/uaa
      options: --privileged --tty --interactive --shm-size=1G
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Integration tests on postgresql version 15
        run: /root/uaa/scripts/integration-tests.sh postgresql,default
        continue-on-error: true
      - name: Test result upload
        uses: actions/upload-artifact@v3
        with:
          name: Server test
          path: /root/uaa/*/build/reports/tests/test/

