name: JUnit tests on database
on:
  pull_request:
    branches: [ develop ]

permissions:
  pull-requests: read

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database: [ 'postgresql-15', 'postgresql-16', 'postgresql-17', 'postgresql-18', 'mysql-8.0', 'mysql-8.4', 'mysql-9' ]
    container:
      image: cfidentity/uaa-${{ matrix.database }}
      volumes:
        - ${{ github.workspace }}:/root/uaa
      options: --privileged --tty --interactive --shm-size=1G
    steps:
      - name: Set env
        run: echo "PROFILE=$(echo ${{ matrix.database }} | sed 's/-[0-9.]*//g')" >> $GITHUB_ENV
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: JUnit tests on container
        id: testrun
        run: /root/uaa/scripts/unit_tests.sh ${PROFILE},default
        continue-on-error: true
      - name: Test result upload
        uses: actions/upload-artifact@v6
        if: steps.testrun.outcome == 'failure'
        with:
          name: Server test
          path: /root/uaa/*/build/reports/tests/test/
      - name: Check error Result
        run: exit 1
        if: steps.testrun.outcome == 'failure'